name: Lint & Test and Merge to Dev

on:
  push:
    branches:
      - test

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter (flake8)
        run: flake8 .

      - name: Run Unit Tests
        run: python -m unittest discover tests

  merge-to-dev:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge test into dev
        run: |
          git fetch origin
          git checkout dev
          git merge origin/test --no-ff -m "Auto-merge from test to dev via GitHub Actions"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/MaemoonFarooq/MLOPS_Project dev
